### ISSUE TITLE
Notification on WebSocket connection status

### ISSUE THREAD

**Issue by pjotrsavitski** [learning-layers/timeliner#77]
Implement a clear notification for status of WebSocket connection.

It could be an icon within the main toolbar that is always visible and gives a clear overview of WebSocket current connection state. Colour codes could be used to further differentiate the status.

Example:
 * green - for connected
 * orange - for not connected, but reconnect being in process
 * red - fully disconnected or more than some threshold of reconnects

Icons: server-network and server-network-off icons should be good enough for starters; possible alternative could be lan-connect, lan-disconnect and lan-pending (these icons clearly cover all the possible states).

**Comment by sanderaido** [comment]
I would suggest we only show the notification when you are reconnecting or disconnected, when socket is running and everything is working fine we don't show any indicator. Otherwise it looks a little like we expect the socket to go down at some point and being "connected" is a special occasion. Maybe we can use it for testing and the first release, but otherwise when everything is working as it should, it's kind of redundant to show the user every time that "hey, our thing is working like it should, congrats". 

I would also apply this logic to everywhere else, where the outcome of the action is as expected (for example any Resource/Outcome/whatever add/update dialog) - when update succeeded (which is the normal and expected behaviour), congratulating a user each time that our system is actually working as it should seems a little unnecessary (and would get annoying over time as well - if it works, great - no need to tell me every time I do something). Gives a more professional feel as well.

But ultimately this should be decided by @vtomberg

**Comment by pjotrsavitski** [comment]
The socket was not meant to be used for unauthenticated users. Make sure that it works without much issues, best choice would be to only start the socket once user is logged in, but it could be as it is for now.
